-- DIMENSIONS
CREATE OR REPLACE TABLE DIM_DATE (
  DATE_KEY      NUMBER(8,0) PRIMARY KEY,   -- e.g., 20260131
  DATE_VALUE    DATE NOT NULL,
  DAY_NAME      VARCHAR(10),
  WEEK_OF_YEAR  NUMBER(2,0),
  MONTH_NUM     NUMBER(2,0),
  MONTH_NAME    VARCHAR(10),
  QUARTER_NUM   NUMBER(1,0),
  YEAR_NUM      NUMBER(4,0),
  IS_WEEK     BOOLEAN); 
 
CREATE OR REPLACE TABLE DIM_CHANNEL (
  CHANNEL_KEY   NUMBER AUTOINCREMENT PRIMARY KEY,
  CHANNEL_NAME  VARCHAR(50) UNIQUE NOT NULL
);
 
CREATE OR REPLACE TABLE DIM_GEOGRAPHY (
  GEO_KEY       NUMBER AUTOINCREMENT PRIMARY KEY,
  CITY          VARCHAR(80),
  STATE_REGION  VARCHAR(80),
  COUNTRY       VARCHAR(80)
);
 
CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
  CUSTOMER_ID   VARCHAR(50) UNIQUE NOT NULL,
  CUSTOMER_NAME VARCHAR(120),
  SEGMENT       VARCHAR(40),
  GEO_KEY       NUMBER REFERENCES DIM_GEOGRAPHY(GEO_KEY)
);
 
CREATE OR REPLACE TABLE DIM_CATEGORY (
  CATEGORY_KEY  NUMBER AUTOINCREMENT PRIMARY KEY,
  CATEGORY_NAME VARCHAR(100) UNIQUE NOT NULL
);
 
CREATE OR REPLACE TABLE DIM_PRODUCT (
  PRODUCT_KEY   NUMBER AUTOINCREMENT PRIMARY KEY,
  SKU           VARCHAR(60) UNIQUE NOT NULL,
  PRODUCT_NAME  VARCHAR(200),
  BRAND         VARCHAR(100)
);
 
CREATE OR REPLACE TABLE BRIDGE_PRODUCT_CATEGORY (
  PRODUCT_KEY   NUMBER REFERENCES DIM_PRODUCT(PRODUCT_KEY),
  CATEGORY_KEY  NUMBER REFERENCES DIM_CATEGORY(CATEGORY_KEY),
  PRIMARY KEY (PRODUCT_KEY, CATEGORY_KEY)
);
 
CREATE OR REPLACE TABLE DIM_PROMO (
  PROMO_KEY     NUMBER AUTOINCREMENT PRIMARY KEY,
  PROMO_CODE    VARCHAR(50),
  PROMO_TYPE    VARCHAR(50),
  DISCOUNT_PCT  NUMBER(5,2)
);
 
-- FACTS

CREATE OR REPLACE TABLE FACT_SESSIONS (
  SESSION_ID    NUMBER(38,0) PRIMARY KEY,
  DATE_KEY      NUMBER(8,0) REFERENCES DIM_DATE(DATE_KEY),
  CHANNEL_KEY   NUMBER REFERENCES DIM_CHANNEL(CHANNEL_KEY),
  CUSTOMER_KEY  NUMBER REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),
  IS_CONVERTED  BOOLEAN DEFAULT FALSE
);

 
CREATE OR REPLACE TABLE FACT_ORDERS (
  ORDER_ID        NUMBER PRIMARY KEY,
  ORDER_DATE_KEY  NUMBER(8,0) REFERENCES DIM_DATE(DATE_KEY),
  CUSTOMER_KEY    NUMBER REFERENCES DIM_CUSTOMER(CUSTOMER_KEY),
  CHANNEL_KEY     NUMBER REFERENCES DIM_CHANNEL(CHANNEL_KEY),
  PROMO_KEY       NUMBER REFERENCES DIM_PROMO(PROMO_KEY),
  ORDER_STATUS    VARCHAR(30),
  PAYMENT_METHOD  VARCHAR(30)
);
 
CREATE OR REPLACE TABLE FACT_ORDER_ITEMS (
  ORDER_ID        NUMBER       REFERENCES FACT_ORDERS(ORDER_ID),
  PRODUCT_KEY     NUMBER       REFERENCES DIM_PRODUCT(PRODUCT_KEY),
  QUANTITY        NUMBER       NOT NULL,
  UNIT_PRICE      NUMBER(12,2) NOT NULL,
  DISCOUNT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  COST_AMOUNT     NUMBER(12,2) NOT NULL,
  PRIMARY KEY (ORDER_ID, PRODUCT_KEY)
);
 
---------------------------------***************************------------------------------------------------------------------------
-- dim_date (3-day window)
INSERT INTO DIM_DATE (DATE_KEY, DATE_VALUE, DAY_NAME, WEEK_OF_YEAR, MONTH_NUM, MONTH_NAME, QUARTER_NUM, YEAR_NUM, IS_WEEK ) VALUES
(20260227, '2026-02-27'::DATE, 'Fri', 9, 2, 'Feb', 1, 2026, FALSE),
(20260228, '2026-02-28'::DATE, 'Sat', 9, 2, 'Feb', 1, 2026, TRUE),
(20260301, '2026-03-01'::DATE, 'Sun', 9, 3, 'Mar', 1, 2026, TRUE);
 
-- channels
INSERT INTO DIM_CHANNEL (CHANNEL_NAME) VALUES ('Web'), ('Mobile App'), ('Store');
 
-- geography
INSERT INTO DIM_GEOGRAPHY (CITY, STATE_REGION, COUNTRY) VALUES
('Chennai','TN','India'), ('Bengaluru','KA','India'), ('Hyderabad','TS','India');
 
-- customers
-- NOTE: assumes GEO_KEY generated 1.. in insert order above
INSERT INTO DIM_CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, SEGMENT, GEO_KEY) VALUES
('CUST-001','Akash Kumar','Consumer', 1),
('CUST-002','Priya Singh','SMB',      2),
('CUST-003','Ravi Iyer','Consumer',   1);
 
-- categories
INSERT INTO DIM_CATEGORY (CATEGORY_NAME) VALUES ('Electronics'), ('Accessories'), ('Home');
 
-- products
INSERT INTO DIM_PRODUCT (SKU, PRODUCT_NAME, BRAND) VALUES
('SKU-100','Wireless Headphones','SoundX'),
('SKU-200','Phone Case','GuardIt'),
('SKU-300','Smart Speaker','EchoSphere');
 
-- product↔category bridge
INSERT INTO BRIDGE_PRODUCT_CATEGORY (PRODUCT_KEY, CATEGORY_KEY) VALUES
(1, 1), -- Headphones -> Electronics
(2, 2), -- Phone Case -> Accessories
(3, 1), -- Smart Speaker -> Electronics
(3, 3); -- Smart Speaker -> Home
 
-- promos
INSERT INTO DIM_PROMO (PROMO_CODE, PROMO_TYPE, DISCOUNT_PCT) VALUES
('NEW10','Coupon',10.00), ('CLEAR20','Clearance',20.00), (NULL,'NoPromo',0.00);
 
-- sessions (some convert, some not)
-- channel_key mapping from DIM_CHANNEL insert order: Web=1, Mobile App=2, Store=3
INSERT INTO FACT_SESSIONS (SESSION_ID, DATE_KEY, CHANNEL_KEY, CUSTOMER_KEY, IS_CONVERTED) VALUES
(1001, 20260227, 1, 1, FALSE),
(1002, 20260227, 1, 2, TRUE),
(1003, 20260227, 2, 3, FALSE),
(1004, 20260228, 1, 1, TRUE),
(1005, 20260301, 2, 2, FALSE),
(1006, 20260301, 2, 2, TRUE);
 
-- orders
INSERT INTO FACT_ORDERS (ORDER_ID, ORDER_DATE_KEY, CUSTOMER_KEY, CHANNEL_KEY, PROMO_KEY, ORDER_STATUS, PAYMENT_METHOD) VALUES
(50001, 20260227, 2, 1, 1, 'Completed', 'Card'),
(50002, 20260228, 1, 1, 3, 'Completed', 'UPI'),
(50003, 20260301, 2, 2, 2, 'Completed', 'Card');
 
-- order_items
INSERT INTO FACT_ORDER_ITEMS (ORDER_ID, PRODUCT_KEY, QUANTITY, UNIT_PRICE, DISCOUNT_AMOUNT, COST_AMOUNT) VALUES
-- Order 50001 (Priya via Web) uses NEW10 coupon
(50001, 1, 1, 3000.00, 300.00, 1800.00),
(50001, 2, 2,  300.00,  30.00,  120.00),
-- Order 50002 (Akash via Web) no promo
(50002, 3, 1, 4000.00,   0.00, 2500.00),
 
-- Order 50003 (Priya via Mobile App) CLEAR20
(50003, 2, 1,  300.00,  60.00,   60.00),
(50003, 3, 1, 4000.00, 800.00, 2500.00);
