name: Read Csv

on:
  push:
    paths:
      - 'models/**'
      - 'macros/**'
      - 'seeds/**'
      - 'snapshots/**'
      - 'dbt_project.yml'
  workflow_dispatch:

jobs:
  run-workflow:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pandas snowflake-connector-python openpyxl dbt-snowflake

      - name: Create dbt profile
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          default:
            target: dev
            outputs:
              dev:
                type: "snowflake"
                account: "JZBSADH-CG45326"
                user: "monopoly22"
                password: "8638569740picklU"
                role: "ACCOUNTADMIN"
                database: "DBT_POC"
                warehouse: "COMPUTE_WH"
                schema: "DBT_SCHEMA"
                threads: 4
          EOF

      - name: Run dbt Models
        run: |
          dbt deps
          dbt run

      - name: Run Python Script
        run: python python.py

      - name: Commit and Push Generated Excel
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data_comp.xlsx
          git commit -m "Auto-generate Excel report from workflow" || echo "No changes to commit"
          git push
      - name: Run Python Script
        run: python Analysis.py
      - name: Commit and Push Generated AI Analysis
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add analysis_report.txt
          git commit -m "Auto-generate Excel report from workflow" || echo "No changes to commit"
          git push
      - name: Trigger Email
        run: python Email.py
