version: 2

sources:
  - name: ecommerce
    database: DBT_POC
    schema: DBT_SCHEMA

    tables:
      - name: dim_customer
      - name: dim_product
      - name: dim_date
      - name: dim_channel
      - name: dim_geography
      - name: fact_orders
      - name: fact_order_items

